version: '2.1'

services:
  broker:
    image: johnnypark/kafka-zookeeper:2.6.0
    container_name: service-broker
    restart: always
    ports:
      - "2181:2181"
      - "9092:9092"
    environment:
    - ADVERTISED_HOST=service-broker
    - NUM_PARTITIONS=3
    networks:
    - aforo255-test
  tracer:
    image: openzipkin/zipkin:2
    container_name: service-tracer
    restart: always
    ports:
      - "9411:9411"
    networks:
    - aforo255-test
  metrics:
    image: prom/prometheus:v2.31.1
    container_name: service-metrics
    restart: always
    ports:
    - 9090:9090
    networks:
    - aforo255-test
    volumes:
    - G:/aforo255/prometheus.yml:/etc/prometheus/prometheus.yml
  analytics:
    image: grafana/grafana:8.2.3
    container_name: service-analytics
    restart: always
    ports:
    - 3000:3000
    networks:
    - aforo255-test
    depends_on:
    - metrics

networks:
  aforo255-test:
    name: aforo255-test